### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bingoxo** [loudKode/Uptobox-Client#1]
I get this error when i login with my account : https://i.imgur.com/Y0DNkfr.png

and the full message : https://privatebin.net/?9b08f3071e36dc11#E9deXtWVKWzcMfmr2bB42USsqGsaDHWduirCYumcLUcc

**Comment by loudKode** [comment]
fixed 
thanks for leting me know

**Comment by bingoxo** [comment]
still not fixed : https://i.imgur.com/NefwLYe.png

**Comment by loudKode** [comment]
fixed

**Comment by bingoxo** [comment]
with 1.6.0 it showed me error at first but then it works now , i'm closing

**Comment by loudKode** [comment]
> with 1.6.0 it showed me error at first but then it works now
fixed in 1.7.0
