### ISSUE TITLE
Cannot download file if there is non english character in file name

### ISSUE THREAD

**Issue by alr2413** [loudKode/Uptobox-Client#2]
Hi, Thanks for providing this utility.
Whenever I try to download a file that has non english characters in its name, the following error occurs:

```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at Uptobox_Client.MainForm.VB$StateMachine_30_MB_Download_Click.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

Please if you have time, fix this issue.

**Comment by loudKode** [comment]
i tried to download a non english file located in a non english directory and it works no problem
show me exactly the case you facing
![https://i.postimg.cc/fTGFfT5B/ure-Wiz798.png](https://i.postimg.cc/fTGFfT5B/ure-Wiz798.png)

**Comment by alr2413** [comment]
Thanks.
Here is the file URL that I had problem with it:
[Mp4 file]( https://uptobox.com/0fwuegnbxe8t)

And this is the screenshot of file:
![Bug](https://user-images.githubusercontent.com/10116275/68273847-c805f600-007c-11ea-8ce7-df0c15090b18.png)

First, I think that it is because of the existence of non-english characters in file name, but now I'm suspicious of "OR" operand character ( || ) in the file name.

**Comment by loudKode** [comment]
fixed ..download latest release and test then close the issue if ok
those aren't (non-english characters) its illegal characters by windows platform
for example:

> // The following characters are invalid in a path:
> // Char    Hex Value
> // ",      0022
> // <,      003C
> // >,      003E
> // |,      007C
> // ...
> //
> // The following characters are invalid in a filename:
> // Char    Hex Value
> // ",      0022
> // <,      003C
> // >,      003E
> // |,      007C
> // ...

**Comment by alr2413** [comment]
Thanks.
It now works.
